out=[]
def w(s=""): out.append(s)
def tbl(h,rows):
    w("| "+" | ".join(h)+" |"); w("|"+"|".join(["---"]*len(h))+"|")
    for r in rows: w("| "+" | ".join(str(c) for c in r)+" |")
    w()
w("## 15. RECOMMENDED BASELINE (not implemented — derived only from the observations above)"); w()
w("**Constraint reminder from the README:** `candidate_pairs.tsv` must be *exactly* the set the classifier scores, so the retriever’s K directly sets that file’s size (K=50 → ≈87 M IDs ≈ 1 GB); the final model must be MIT/Apache-2.0 and ≤8 B parameters (gradient-boosted trees satisfy this trivially).")
w()
w("**Step 0 — Loading.** `pd.read_csv(sep='\\t', dtype=str, keep_default_na=False, na_filter=False, quoting=csv.QUOTE_NONE)`; convert once to parquet; keep IDs as (source, int) pairs. *(Why: names `NA`/`Na`/`null` and empty addresses are real values; 134–349 lines per test file contain a bare `\"`.)*")
w()
w("**Step 1 — Normalisation (per field, deterministic; country-aware dictionaries, global fallback).**")
w("- *Cleaning:* map `\\x1A`/`\\x7F` → space, repair `Â\\x80\\x93/\\x99` → `-`/`'`, drop `&#65533;`, NFKC, casefold, fold Latin diacritics only (never Indic combining marks), punctuation → space, collapse whitespace.")
w("- *Names:* strip `(ID: 12345)` / trailing `#12345`, leading junk punctuation and honorifics (`Mr/Mrs/Shri/Smt/Sri/M/s`); resolve **alias markers** (`dba|d/b/a|f/k/a|fka|a/k/a|aka|t/a|trading as|formerly`) by keeping the text *after* the marker as the core name (the true S1 name is there in 99.9% of alias cases) and the text before as a weak secondary field; turn `xxx.com`/`www.` into its stem; **pull the legal form out of the name** (`pvt|private|ltd|limited|llc|l.l.c|llp|inc|incorporated|corp|corporation|co|company|pllc|pc|sarl|sas|sasu|eurl|sci|sa…` → canonical type) and compare *core names* and *legal types separately* (a dropped suffix is the most common difference, 22%, and must not be penalised like a mismatch — but a *conflicting* legal form is 13× enriched among false candidates); `&`↔`and`; keep both ordered and token-sorted forms (6% pure word-order changes; suffix words move to the front/middle).")
w("- *Addresses:* drop `NULL/<NULL>/N/A`; move `PO BOX/PMB/Unit/#/Apt/Floor` tokens into a separate ‘secondary’ field; strip leading zeros from numbers (`0014048` → `14048`); extract the **first house/plot number token(s) as their own feature** (equal in 79%, 83% after zero-strip); expand street-type abbreviations with a dictionary (`rd/road, st/street, ave, dr, ln, ct, cir, blvd, hwy…`); map **state code ↔ full name ↔ native-script name** and India district/city variants (`Madras/Chennai`, `Bangalore/Bengaluru`, `Ahmadabad/Ahmedabad`) with equivalence tables **mined from aligned training positives** (S1 last component vs S2/S3 components) rather than hand-typed; sort components (5–8% pure reorders).")
w("- *France (no labels):* accent folding, `R./Rue`, `Av/Avenue`, `Bd/Bvd/Boulevard`, `Pl./Place`, `Allée/Allee`, `S.A.S/SAS`, `S.A.R.L/SARL`, treat `de/du/des/la/le` as stop-tokens (they are the top address tokens) — derived from the test S1/S2/S3 text distributions, not from train.")
w()
w("**Step 2 — Blocking (within `country` string equality; union of channels; top-K by IDF score).** (a) *exact tier*: equal token-sorted normalised address, or equal token-sorted normalised name (finds ≈47% of positives and is very precise *when the address/name is not shared by several S1 entities*); (b) *address channel*: sparse IDF-weighted token overlap; (c) *name channel*: IDF-weighted name tokens + 4-char prefixes (typo tolerance); (d) for records with a native-script name only the address channel applies. Rank by summed IDF, keep K≈30–50 per entity; expected match-level recall from the simple version measured here: **≈ 93–96% US, ≈ 87–91% India at K = 20–100** (oracle macro-F0.5 ceiling 0.97 at K=100). IDF must be **country-specific** (a token like `bordeaux` or `rue` has a different df in each pool). Do not use ZIP/PIN (absent), state alone, or first-token keys as the sole blocker.")
w()
w("**Step 3 — Pair features (≈30–40, computed on Step-1 fields).** *Name:* `token_sort/set/partial ratio`, Jaro-Winkler, normalised Levenshtein, token Jaccard/overlap, **char-3-gram TF-IDF cosine** (best single name feature: AUC 0.987 on Latin names), core-name similarity, legal-type agreement and a **legal-form *conflict* flag** (13× enriched among dangerous false candidates), first-token equality, length/token-count deltas, flags for native-script / domain-form / alias / initials-only (≤2-char) names, ‘S1 name shared by n other S1 entities’. *Address:* token-set ratio, Jaccard, IDF-weighted overlap, char-3-gram TF-IDF cosine, **house-number equal / equal-after-zero-strip / off-by-one-edit**, state agreement, city/locality token agreement, missing/extra component counts, empty-address flag. *Context:* source (S2 vs S3 — their noise styles differ), country, retrieval rank/score/relative score/gap to next candidate, **competition features** (number of S1 entities for which this S2/S3 record is a candidate; whether this S1 is the record’s best-scoring S1).")
w()
w("**Step 4 — Classifier.** Gradient-boosted trees (LightGBM/XGBoost, or scikit-learn `HistGradientBoostingClassifier`, which already gave AUC 0.998 on sampled pairs and macro-F0.5 ≈ 0.89 in the end-to-end diagnostic below). Missing address → native `NaN`. **Train on the retriever’s candidate lists (with decoys and sibling look-alikes), not on random negatives** — random negatives are trivially separable (AUC 0.91–0.99 per single feature) and would over-state precision; positives are ≈3–4% of a top-100 list.")
w()
w("**Step 5 — Decision rule.** (i) score each candidate; (ii) enforce the **one-to-one property** observed in ground truth (each S2/S3 record ↔ at most one S1): a record is offered only to the S1 entity where it scores highest (drop on near-ties); (iii) predict candidates with p ≥ τ, tuned by **macro F0.5 over grouped validation entities including singletons** — in the diagnostic the optimum was flat at τ≈0.6–0.7; (iv) keep exact in-source duplicates (identical name+address+country within S2 or S3) together — they always share one S1 owner; (v) return an empty list when no candidate clears τ.")
w()
w("**Step 6 — Validation protocol.** Split **by S1 entity** (all its matches in the same fold; names are template-generated so row-level splits leak), evaluate on candidate lists built from the *full* S2/S3 pool (decoys included), report macro-F0.5 separately for US/India, S2/S3, singleton/non-singleton and native-script/Latin; **leave-one-country-out (train US → test India and vice-versa)** as the only available proxy for the unseen France domain.")
w()
w("**What this baseline should be expected to reach:** the end-to-end diagnostic (K=100 IDF retrieval + 19 features + boosted trees trained on only 1,200 entities/country, no one-to-one rule, no context features) scored **macro-F0.5 ≈ 0.89** on held-out entities (US 0.94, India 0.85; singletons 0.80–0.85 at the optimal τ). A properly built version of Steps 1–5 should do materially better; the gap to the 0.97 oracle ceiling is concentrated in India, in singletons (sibling look-alikes) and in native-script/alias names.")
w()
w("## 16. RECOMMENDED ADVANCED PIPELINE — what to investigate next (and what the data says *not* to spend time on)"); w()
tbl(["technique","verdict from the data","why / what to test"],[
 ["Fuzzy string matching (RapidFuzz etc.)","**Yes — core**","Most positives need fuzzy comparison (only 4.6% identical names). Token-set/partial ratio and Jaro-Winkler are strong; plain Levenshtein is the weakest name feature (AUC 0.90 vs random) and fails on order changes."],
 ["TF-IDF (word and char n-gram)","**Yes — for retrieval *and* features**","Char-3-gram TF-IDF is the best single name feature (AUC 0.987 Latin) because typos/leet/accents break tokens but not trigrams; address TF-IDF is the best single address feature (0.956). Fit IDF per country on S2∪S3."],
 ["Character n-grams / MinHash-LSH","**Yes as a second retrieval channel**","Complements token retrieval for typo-heavy names; candidate to close part of the India recall gap (90.7% @100). Needs a native-script-aware analyzer."],
 ["Sentence/multilingual embeddings","**Not as the main matcher; test narrowly for native-script names**","Name noise is orthographic (typos, order, suffix), not semantic, and names are built from a small template vocabulary — semantic similarity would merge siblings (`Goodwill Academy` / `Goodwill Academy Exports`). The one place they may pay off is **Devanagari/Telugu/Tamil/… ↔ Latin** (18% of India positives; 9% of S2, 5% of S3 names). Compare against a **learned token-level translation table mined from the 7.6 M training pairs** (cheaper, exact; India OOV is only ≈1.1%). Any model must be MIT/Apache and ≤ 8 B."],
 ["GBDT (XGBoost / LightGBM / HistGB)","**Yes — first model**","Heterogeneous numeric features, ~4–5% missing address, class imbalance in candidate lists, need for calibrated probabilities for an F0.5 threshold."],
 ["Second-stage / listwise model","**Yes**","Aggregate over an entity’s candidate list (score gaps, #candidates above τ, competitors at the same address, one-to-one conflicts, S2–S3 mutual agreement). This is where sibling decoys and same-address entities are resolved."],
 ["Ensembles","Later","Country-specific vs global GBDTs, name-only + address-only + joint models; likely small gains over good features."],
 ["Threshold optimisation","**Yes — high value**","Macro-F0.5 with 5.6% singletons: tune τ per source (S2/S3), per evidence type (native-script name, empty address), and consider choosing each entity’s predicted set to maximise *expected* F0.5 given candidate probabilities (≤11 matches; a false match costs ≈2.3× a miss, and 1.0 on a singleton)."],
 ["Source-specific handling","**Yes**","S2 and S3 differ systematically (S2: ALL-CAPS, reorders, drops components, no DBA aliases, 12.5% exact-normalised address matches; S3: spelled-out US states, India 2-letter states, DBA aliases, 4.3% exact addresses). Add `source` as a feature at minimum; test separate models."],
 ["Country-aware processing","**Yes, with a global fallback**","Separate normalisers/IDF/threshold *tables* keyed by the country string; no one-hot on {US, India}. Validate transfer with leave-one-country-out. For France: unsupervised dictionaries from test text (check the competition rules on fitting unsupervised statistics on test data before doing this; document it)."],
 ["Graph / cluster consensus","**Worth testing**","S2/S3 records of one entity are similar to each other (and exact in-source duplicates always share an owner); use S2↔S3 similarity as evidence for borderline candidates and to break one-to-one conflicts."],
 ["Postal-code / geocoding features","**No**","No ZIP/PIN/postcodes exist in any file; geocoding APIs are prohibited."],
 ["Global neighbour-graph or LLM matching","No (too expensive at 10⁷ records; ≥8 B limits)","Pair volume (35–170 M scored pairs) favours cheap features + trees."]])
w("**Concrete next investigations (ordered by expected value):** (1) dissect the India recall gap at K=100 (native names? reordered long addresses? mutated numbers?); (2) mine abbreviation/state/city/transliteration equivalence tables from aligned positives and measure coverage on test tokens; (3) build features that separate **sibling decoys** from true matches with mutated house numbers (unit-number conflict × suffix-word conflict × source); (4) implement the one-to-one assignment and measure how much of the singleton false-positive rate it removes; (5) quantify France: token-frequency profile, expected duplicate-name/address ambiguity, initials-only names, and whether the exact tier alone yields a high-precision first pass for pseudo-checking; (6) calibrate probabilities and choose τ by grouped-validation macro-F0.5.")
w()
w("## 17. MEMORY / PERFORMANCE"); w()
tbl(["item","measured / estimated"],[
 ["Raw TSV size","train 1.20 GB (S1 0.21 + S2 0.49 + S3 0.50) + ground truth 0.13 GB; test 1.19 GB (0.18 + 0.51 + 0.51); total ≈ 2.5 GB (decimal)"],
 ["In pandas RAM (object strings)","train S1 0.63 GB, S2 1.58 GB, S3 1.63 GB, GT 0.34 GB; test S1 0.52 GB, S2 1.61 GB, S3 1.62 GB — **≈ 8.0 GB for all seven**"],
 ["Fits in 16 GB?","**Yes for loading, no for everything at once with derived columns.** Load once → parquet (2–6 s per file), process **per country** and per source, use `string[pyarrow]`/categoricals for `country`, int64 for ID numbers. Peak in my retrieval experiments ≈ 5 GB."],
 ["Parsing","TSV → pandas 2–6 s per file (C engine, `dtype=str`); no chunking needed for parsing"],
 ["Normalisation (`ext`, regex with callbacks)","≈ 40–65 s per 5 M-record source for name + address (measured 27 s for the 2.2 M-record S1); chunk at 0.4–1 M rows"],
 ["Vectorising (CountVectorizer, 3 views)","≈ 30 s per country over the 4–6 M-record pool; sparse matrices 15–42 M non-zeros per view (≈ 0.2–0.5 GB each)"],
 ["Token retrieval (sparse product, top-K)","**≈ 45 ms (US) / 78 ms (India) per S1 entity on one core** → ≈ 30 core-hours for 1.73 M test entities naive; ≈ 3 h on 10 cores. Needs batching (100–500 entities), df cut-off (20k), float32, `multiprocessing` per country/chunk — or an exact-tier-first design that only retrieves for unresolved entities"],
 ["Pair features (RapidFuzz + Python)","≈ 58 µs/pair for 19 features (600k pairs in 35 s) → K=50: 87 M pairs ≈ 1.4 core-hours; K=100: 173 M ≈ 2.8 core-hours (≈ 17 min on 10 cores). Vectorise with `rapidfuzz.process.cdist` per chunk; never `df.apply(axis=1)`"],
 ["Feature matrix","173 M pairs × 40 float32 = 28 GB → **must stream** in 1–2 M-pair chunks (score, keep p and IDs, discard features)"],
 ["Brute-force pair space","test 1.7×10¹³ (6.7×10¹² same-country); train 2.3×10¹³ (1.2×10¹³ same-country) — never enumerate"],
 ["Realistic candidate scale","K = 20 → 35 M; 30 → 52 M; 50 → 87 M; 100 → 173 M test pairs; the exact-address/name tier adds well under 1 pair per entity"],
 ["Expensive vs cheap","Cheap: exact-key joins, groupby, value_counts, ground-truth explode (7.6 M pairs, seconds). Expensive: retrieval matmul, per-pair fuzzy features, regex-callback normalisation, TF-IDF fitting on all 10 M records (use a 0.5–1 M sample)."]])
w("## 18. FINAL EXECUTIVE SUMMARY"); w()
w("**DATASET SIZE:** Train: 2,206,821 S1 / 5,034,616 S2 / 5,285,603 S3 records, 7,638,365 true pairs. Test: 1,732,544 S1 / 4,887,273 S2 / 5,082,316 S3 records (≈ 11.7 M records, 1.19 GB; every S1 needs a row). 2.5 GB of TSV in total; fits in 16 GB RAM if processed per country. Clean file format (0 malformed rows, 0 duplicate IDs, valid UTF-8).")
w()
w("**MAIN NOISE TYPES:** Names — case/whitespace/punctuation (≈17%), abbreviation & legal-suffix swaps/drops (`Ltd/Limited`, `Corp/Corporation`, `Co/Company`, `Inc→Incorporated`, `LLC→L.L.C.`; suffix dropped in 22% of pairs; note `Pvt`↔`Private` is *listed* in the task but **never flips** in the data), word-order shuffles (6%), typos and digit-for-letter swaps, diacritic injection, honorifics/fake `(ID: n)` suffixes/junk prefixes/domain-style names (`xxx.com`), DBA/F/K/A aliases (S3), duplicated/added/dropped words (~25%), **full native-script rewrites (18% of India pairs)** and unrelated aliases/2-letter initials (~4%). Addresses — ALL-CAPS and abbreviations (S2), spelled-out US states / 2-letter India states (S3), reordered components, `NULL/N/A` fillers, `PO BOX/PMB`, zero-padded and **mutated house numbers (17% of pairs)**, dropped/misspelled/substituted cities (11–12%), missing state (15% of S3 US), native-script states, empty address (4.4%). **No ZIP/PIN codes anywhere.**")
w()
w("**MATCH DENSITY:** 3.46 matches per S1 entity (3.67 excluding singletons), median 3, max 11; S2 1.67 + S3 1.79 per entity; 80.5% of entities have matches in both sources; only 5.4% have exactly one. 73–75% of S2/S3 records are matched (each to exactly one S1 — a strict partition), 26% are decoys. Test has ≈ 24% more S2/S3 records per S1 and appears to have ≈ 41% decoys.")
w()
w("**SINGLETON RATE:** 5.585% (123,247), identical in US and India, statistically unrelated to any S1 attribute. A false match on a singleton costs 1.0 of that entity’s score (≈ 2.3× a false negative elsewhere). In the diagnostic, 24% of singletons receive a false candidate scored ≥ 0.5 and 4.8% one ≥ 0.95 — mostly engineered sibling look-alikes (same building, near-identical name, different unit number/suffix word).")
w()
w("**MOST IMPORTANT SIGNALS:** (1) **Address token overlap** — every non-empty matched address shares ≥ 1 token; address TF-IDF AUC 0.956, and it is the only signal separating same-name entities (38% of S1 rows share a name). (2) **Name char-n-gram/token similarity** — AUC 0.987 on Latin names but only 0.83–0.86 overall (native/alias names). (3) **House/plot number equality** (79–83%). (4) **Country equality** (100% of positives). (5) Source identity (S2 vs S3 noise styles). (6) Structure: one-to-one partition, in-source exact duplicates ⇒ same owner, empty address ⇒ 97.8% matched. Name and address are complementary: either ≥ 0.8 for 91% of positives; neither usable for only ≈ 1%.")
w()
w("**BIGGEST CHALLENGE:** Precision on look-alikes — sibling decoys and same-name/same-address entities whose distinguishing evidence (a unit number, a suffix word) is the same kind of perturbation the noise generator applies to true matches — compounded by (a) **France**, ≈ 15% of test entities, with no training data, 53% OOV name tokens, more name/address duplication and a new initials-only-name noise, and (b) India recall (native-script names, long shuffled addresses), which is ≈ 5 points below the US at every K.")
w()
w("**RECOMMENDED FIRST MODEL:** Normalisation (legal-form extraction, alias/ID/domain stripping, abbreviation + state maps, house-number feature) → per-country IDF retrieval (top-K 30–50 from address + name-token/prefix channels + exact tier) → ~35 name/address/context features → gradient-boosted trees trained on retriever candidate lists with grouped-by-S1 validation → one-to-one assignment + macro-F0.5-optimised threshold (≈ 0.6–0.7 in the diagnostic). Diagnostic version of this already gave macro-F0.5 ≈ 0.89 (US 0.94, India 0.85).")
w()
w("**RECOMMENDED BLOCKING:** `country` string equality, then a union of (a) exact token-sorted address/name equality, (b) IDF-weighted address-token retrieval, (c) IDF-weighted name-token + 4-char-prefix retrieval, ranked and cut at K ≈ 30–50 (recall ≈ 93–96% US, 87–91% India in the simple version; ≈ 35–90 M test pairs). Avoid first-token/first-N-char keys (2–14 k candidates/entity), state or city keys, house-number-only keys (lose 23–34%), and any rare-token rule with df ≤ 300 (≤ 65% recall).")
w()
w("**POTENTIAL DATA LEAKAGE RISKS:** *Not found:* ID values, ID length, row order, file position (Spearman ≈ 0, KS ≈ 0.005, ID-length agreement at chance), train/test ID overlap (0), train/test exact (name, address) overlap (0). *Found / to manage:* (1) record-level artefacts that reveal ‘matched’ status (empty address ⇒ 97.8%, `.com` names ⇒ ≈ 96%, shorter names, exact in-source duplicates ⇒ 100%) — legitimate at test time but they inflate validation if negatives are drawn only from matched records and may shift in France; (2) validation splits **must be by S1 entity** — names are template-generated (35% of test S1 names occur in train), so row-level splits leak; (3) random negatives are unrealistically easy (decoys are cleaner/longer than matched records) — train/validate on retrieved candidate lists; (4) the one-to-one partition property is a property of the *training* ground truth; it is unverifiable on test and should be used as a soft/verified assumption; (5) fitting dictionaries/IDF on test text is unsupervised but check the rules and document it.")
w()
w("**QUESTIONS WE SHOULD ANSWER BEFORE MODELING:** (1) Does test follow the same partition and ≈ 3.5 matches/entity, given 24% more S2/S3 per S1 (≈ 41% decoys inferred)? How much precision margin does that require? (2) What transfers to France — can leave-one-country-out and synthetic French noise be trusted as validation? Which French normalisation rules are needed? (3) Native-script names: token-translation table mined from training pairs vs multilingual model — what coverage/accuracy? (4) Can unit-number / suffix-word / legal-form-conflict features separate sibling decoys from true matches with mutated numbers, and what is the ceiling? (5) Where exactly is India’s recall lost at K=100 (90.7%)? (6) Best decision rule for macro-F0.5: global τ vs per-source/evidence τ vs per-entity expected-F0.5 subset selection; how much does the one-to-one rule buy? (7) Can S2↔S3 mutual similarity and in-source duplicates be used as consensus evidence? (8) K and candidate-file size (`candidate_pairs.tsv` ≈ 1 GB at K=50) — acceptable?")
w()
w("---")
w("### Caveats and limitations of this reconnaissance")
w("- Rates marked *(sample)* rest on 150k–500k pairs or 1,500–3,000 entities per country; headline percentages are stable to ≈ ±0.2–1 point, rare-category counts are not.")
w("- The noise taxonomies are heuristic and priority-ordered; compound noise lands in the lowest-priority bucket. ‘Unrelated alias’ (4%) is defined by `token_sort_ratio` < 50, so it also contains some heavy-edit cases.")
w("- The diagnostic model (§9, §11.5, §12) is a measuring instrument trained on tiny samples; its 0.89 is a floor-ish indication of what simple features achieve, not a forecast of leaderboard score, and it has no France information at all.")
w("- Test-set statements about decoy share and France are **inferences from unsupervised proxies**; no test labels exist.")
w("- Candidate-count experiments used same-country pools from the training split; test pools differ in size (US −38%, India +14%).")
w("- Scripts: `analysis_scripts/` holds the main pipeline (`s00`–`s11`, `util.py`) and the report builders; caches (≈3 GB parquet) and intermediate JSON were written to a temporary scratch directory outside the project and are not part of the deliverable. A few small one-off checks were run interactively and are not saved (see the note at the top).")
open("report_D.md","w").write("\n".join(out)); print(len(out))
